# Generated by Django 5.1 on 2024-09-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='preview',
            new_name='photo',
        ),
    ]
