# Generated by Django 5.1 on 2024-09-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=150, verbose_name='Наименование категории')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=150, verbose_name='Наименование товара')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='catalog/photo', verbose_name='Фото')),
                ('price', models.IntegerField(blank=True, help_text='Укажите цену за покупку', null=True, verbose_name='Цена за покупку')),
                ('created_at', models.DateField(blank=True, help_text='Укажите дату создания', null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, help_text='Укажите дату изменения', null=True, verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Товары', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
